### ISSUE TITLE
golang1.5中的bug?

### ISSUE THREAD

**Issue by ironboxer** [donng/go-shortenurl#3]
我将代码clone到本地运行，发现respondWithJson方法有问题，虽然Content-Type设置为application/json格式，但是返回的格式依旧是 text/html， 后来返现调换一下两句话的位置就可以了。

有问题的版本
```golang
func respondWithJson(w http.ResponseWriter, code int, payload interface{}) {
	resp, err := json.Marshal(payload)
	if err != nil {
		log.Printf("error: %+v\n", err)
	}

        w.WriteHeader(code)
	w.Header().Set("Content-Type", "application/json")
	
	w.Write(resp)
}
```

没有问题的版本

```golang

func respondWithJson(w http.ResponseWriter, code int, payload interface{}) {
	resp, err := json.Marshal(payload)
	if err != nil {
		log.Printf("error: %+v\n", err)
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(code)
	w.Write(resp)
}
```

需要先setHeader 然后writeHeader 

我的go版本

➜  go-shortenurl brew info go
go: stable 1.15.5 (bottled), HEAD
Open source programming language to build simple/reliable/efficient software
https://golang.org
/usr/local/Cellar/go/1.15.5 (9,784 files, 494.2MB) *
  Poured from bottle on 2020-11-29 at 13:28:21
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/go.rb
License: BSD-3-Clause

**Comment by donng** [comment]
谢谢指正，我在 go 14.1 测试 json 响应头也没有设置成功，应该是有顺序问题，两处都修改了
